lsp-bridge.el

cl-lib: cl-remove-if-not
cl: remove-if-not
And Package cl is deprecated in Emacs-27 #35
https://github.com/kiwanami/emacs-epc/issues/35

Fix remove-if-not is void.

---

lsp-bridge.py

File path from LSP maybe contain quoted char, for example '@' quoted to '%40'

unquote path string from LSP

---

core/lspserver.py
langserver/clangd.json

1. Fix typo.
2. `inlay-hints=true` is only for clangd 13+ and has no effect on lsp-bridge.
3. Try print lsp server exit information for debugging.

Fix clangd server command parameters. (#21)

---

lsp-bridge.el

fix: `length=` introduced at Emacs version 28.1

---

core/utils.py

有些lsp server如ts-ls，Windows下返回的uri会把驱动盘符的:也编码

quote/unquote in path_to_uri/uri_to_path

---

core/lspserver.py

使用 PyRight 时遇到了不少 “NOTE: This is a bug, the second line should be empty”。观察 log 后发现，在 JSON 消息后可能没有任何换行，Content-Length 直接贴在 } 的后面。
所以修复了一下读消息的部分代码，主要变更是（使用 BufferedReader）直接读出 Content-Length 大小的消息，这样就避免了消息被分成两部分时需要的 hack。

Fix receiving messages from lsp servers

---

langserver/hls.json

Fix hls parameters

---

core/lspserver.py

不向已经退出的进程发送消息。这种情况可能会出现在初始化失败的 server 上。

Refrain from sending messages to processes that already exited

---

core/fileaction.py

This pull request fixes an exception using with solargraph:
```
--- Send request (1784): textDocument/completion
--- Recv response (1784): textDocument/completion
Exception in thread Thread-3:
File "/nix/store/nvxp3xmlrxj9sw66dk7l0grz9m4889jn-python3-3.9.12/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/nix/store/nvxp3xmlrxj9sw66dk7l0grz9m4889jn-python3-3.9.12/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/home/xinyifly/.config/emacs/site-lisp/lsp-bridge/lsp-bridge.py", line 109, in message_dispatcher
self.handle_server_message(*message["content"])
File "/home/xinyifly/.config/emacs/site-lisp/lsp-bridge/lsp-bridge.py", line 189, in handle_server_message …
```

fix completion response annotation default

---

core/utils.py

functools.cache 3.9 版本才引入，还是挺新的，lru_cache 适用性更好些吧，3.2 以后都能用

use lru_cache(maxsize=None)

---

lsp-bridge.el

即 lsp-bridge-find-def 等命令之后，可以使用 evil-jump-backward 跳回原处

兼容 evil-jump-backward

---

README.md
README.zh-CN.md
lsp-bridge.el

implement xref backend, so that users can use xref commands to find def and jump around.
commands on README work perfectly.
known problems:
- `xref-find-definitions-other-windows` jump in the origin window instead of the other one

add xref support

---

core/handler/completion.py
lsp-bridge.el

1. 引了个 dash 依赖，看看是不是可以替换；
2. 在 annotation-function 中用来记录了个 prefix 主要是拿 corfu-insert 插入之前的输入前缀，lsp-bridge-completion-prefix 记录的前缀在选中之后就是nil了，直接在 exit-function 中获取的是 corfu-insert 之后的内容，所以目前只想到在哪里能拿到想要的值；

Add support textEdit

---

core/lspserver.py
langserver/dart-analysis-server.json
langserver/gopls.json
lsp-bridge.el

client-capabilities 应该是client 端的能力， 而不应该在 langserver的配置文件中进行配置。
lsp-bridge--client-capabilities 是在 eglot-client-capabilities基础上微调，并以注释的形式保留eglot 大部分楝
`eglot-client-capabilities` 的函数支持传递一个server参数，以便根据不同的server ,调整client 端的capabilities,
lsp-bridge--client-capabilities的实现 目前server 传的是nil （不清楚lsp-bridge有没有相应的server信息)
不过`eglot-client-capabilities` 仅在对tramp的支持上用到了server这个参数,短期不打算支持capabilities的话，影响不大。
后续可以有序的打开各个选项。
目前只配置了 `snippetSupport`的支持。其他选项不了解，作者可后续酌情打开相应的注释。
2. dart-analysis-server.json 中有 snippetSupport相关支持， 现给去掉了。
3. gopls server 端 配置snippet 相关支持，及其他一些选项。
gopls 的一些配置 在
https://github.com/golang/tools/blob/master/gopls/doc/emacs.md  与
https://github.com/golang/tools/blob/master/gopls/doc/settings.md
eglot 的cllient-capabilities 
```
{
"workspace": {
"applyEdit": true, …
```

支持像eglot 一样在elisp 端配置client-capabilities，并全局支持snippet ，并gopls server端配置支持snippet 等

---

lsp-bridge.el

need remove corfu--auto-post-command from post-command-hook if manually enable lsp-bridge-mode
and corfu auto completion already enabled.

fix disable and reenable corfu auto completion

---

core/handler/completion.py

annotation 中删除空格是历史遗留问题，最初与 emacs 通讯需要用空格区分参数。改用 sexpdata 之后不需要这么做了

No need to remove spaces in strings thanks to sexpdata

---

lsp-bridge.el

为回调时候自动弹出补全窗口增加更多限制，包括需要保证和请求补全时候同一状态以及用户自定义函数。比如可以在自己配置里用如下定制满足 corfu 没有选中候选以及 evil 处于 insert 状态才会再弹出补全框
```elisp
(customize-set-variable 'lsp-bridge-enable-popup-predicates
'((lambda ()
(and
(< corfu--index 0) ; not select a candidate
(or (not (featurep 'evil)) (evil-insert-state-p)))))) ; in insert state for evil users
```

Add more constraints for completion popup

---

lsp-bridge.el

移除 **(add-hook 'post-command-hook 'lsp-bridge-monitor-window-buffer-change)** 的 autoload 标签，lsp-bridge-monitor-window-buffer-change 并不是 autoload 函数，如果加载生成的 autoload 文件就会报找不到这个函数的错误，感觉这行代码也不需要  autoload 。

adjust autoload statement

---

core/handler/completion.py
lsp-bridge.el

解决 c 里面 include <|> 补全会多出一个 > 的问题。
原理：如果补全返回的 textEdit 中 range end 比当前补全时的 position 更大，则表示需要删除补全之后的某些字符，因此在补全的 :exit-function 中，将其加到 delete-end-pos 中。测试过 c / python, 暂未发现副作用。

fix additional character after completion

---

lsp-bridge.el

auto-import 之前会报错 void-variable markers, 参考 eglot 处理，修改后可以了。

修正 auto-import 失效

---

lsp-bridge.el

Issue:
As below, I am trying to rename `a` to `abc` with double `a` in the same line.
And it turns to be something like below as the ranges of two candidates overlap.
Solution:
A simple solution is to apply the edit from the bottom to the top by reversing `edits`. It works though I am not sure whether there is side effect.

Fix multiple candidates in one line when renaming

---

acm/acm.el

emacs-plus 28.1在macos下使用straight包管理启动时会有warning

fix warning

---

acm/acm.el

To avoid Emacs29 echo warning message.

Don't quote lambda

---

core/fileaction.py

Fix elixirLS 's completion_item documentation is a markdown dict.

Fix completion_item documentation is markdown (dict).

---

lsp-bridge.el

Avoid exposing internel functions.

---

acm/acm-backend-tempel.el
acm/acm.el

增加了最简单的 orderless 支持。可以自由选择样式。因为需要用户显示设置相关函数，所以也就没加依赖，默认用户已经安装并配置过 orderless 才会有这个需求。

add simple orderless support

---

core/lspserver.py

fix pyright-langserver path err in windows which install by npm

---

acm/acm-backend-elisp.el

这个比较函数总是会把匹配，最短的放前面。之前 “string<" 会把很长的放前面。

sort elisp candidates

---

acm/acm.el

For buffer centering modes, the acm popup at the wrong place
Also there is a typo.

ACM popup, support for buffer centering modes

---

README.md
README.zh-CN.md
langserver/fortls.json
lsp-bridge.el

Add lsp support for `f90-mode`, `fortran-mode` for Fortran language using `fortls` language server.

Add Fortran language support

---

core/handler/hover.py
lsp-bridge.el

Some language server, for example jdtls, don't have `range` key in
textDocument/hover response. According to
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/,
t, `range` is optional in the response of `Hover Request`.

Fix document hover not displaying under some language servers

---

lsp-bridge-ref.el

Use `substitude-command-keys` instead of hard coded keybinding indicator
in header-line of *lsp-bridge-ref* buffer

Use substitude-command-keys in lsp-bridge-ref-update-header-line

---

langserver/pyright.json

将pythonPath中的内容修改为python后，pyright会指定到环境中最先找到的python，这样的话emacs用户只需在打开项目中的python文件后，开启对应的虚拟环境（e.g. pyvenv），再 M-x lsp-bridge-mode 就可以支持python虚拟环境（若已经开启lsp-bridge-mode了，就运行 M-x lsp-bridge-restart-process）
这样的修改比原先wiki中的方法主要好在：绝大多数情况下用户无需修改config中的pythonPath就可以支持虚拟环境，langserver中的配置对于用户更加透明；更简单直观；更好地支持非git submodule 的用户 （wiki中的方法需要给出lsp-bridge/langserver/pyright.json的路径）

修改pythonPath 从而方便地支持python的虚拟环境

---

acm/acm-quick-access.el

only bind keys when quick access is enable
adjust default index order

only bind keys when quick access is enable

---

README.md
README.zh-CN.md
langserver/digestif.json
lsp-bridge.el

include support of a lightweight latex LSP [digestif](https://github.com/astoff/digestif)

include digestif server for latex

---

lsp-bridge-jdtls.el

lsp-bridge-get-lang-server-by-project renamed to lsp-bridge-get-single-lang-server-by-project

Fix lsp-bridge-jdtls.el

---

langserver/emmet-ls-css.json
multiserver/css_emmet.json
multiserver/html_emmet.json

langserver/emmet-ls.json's default config for .html and langserver/emmet-ls-css.json for .css
multiserver/css_emmet.json and multiserver/html_emmet.json for example

fix: add single server: emmet-ls-css and multiserver: css_emmet html_emmet

---

acm/acm.el
lsp-bridge.el

1. remove useless option: lsp-bridge-enable-candidate-doc-preview
2. add command acm-doc-toggle and set keymap
3. hide acm-* commands in M-x cmd

fix: doc preview display

---

acm/acm.el

Use `acm-frame-visible-p` in `acm-doc-toggle` instead

fix: acm-doc-toggle error:frame not exists when acm-enable-doc set to nil

---

core/search_file_words.py

When **tramp ssh buffer** or **kubel buffer** exists, it's path will be `/ssh:xxx@xxx.xxx.xxx.xxx#port:/path/to/file` which will arise FileNotFoundError.

Catch FileNotFoundError when read search files.

---

lsp-bridge.el

Ascertain `acm-backend-lsp-filepath` is not void before lsp-bridge-diagnostics-fetch runs (#296)

---

README.md
README.zh-CN.md
core/lspserver.py
langserver/graphql-lsp.json
langserver/python-ms.json
lsp-bridge.el

This PR adds follows
1. support of GraphQL lsp (needs changes in #310)
2. support of legacy microsoft python language server for Python 2

Legacy Python lsp and GraphQL support

---

acm/acm.el

当 emacs 的窗口比较狭窄时, 会出现  acm menu 的补全框, 在光标的左边, 而且 acm menu 超过了 emacs 的左边边框. 这种情况, 让补全窗口x坐标为 offset-x 应该就行了.

fix: 补全框超过了 emacs frame.

---

lsp-bridge.el

After acm-complete-or-expand-yas-snippet, lsp-bridge still
try to run acm-complete, this will lead cursor to wrong place,
it should stop completion after acm-complete-or-expand-yas-snippet
and hit tab to next snippet field.

Stop completion after acm-complete-or-expand-yas-snippet

---

acm/acm-backend-path.el
lsp-bridge.el

1. 原来的直接使用 keyword 来获取parent-dir 体验不好， 必须从头到尾开始输路径才能补全， 使用 (thing-at-point 'filename) 体验会更好
2. 增加了在字符串中补全目录路径， 一般来说， 路径都是在字符串里的， 没这个支持的话，只能先写好路径再加双引号
3. 这个补丁虽然能在字符串中补全，但是有一个小BUG，如下所示
`"~/emacs_notes/Android/"`  
尝试补全上述路径， 如果Android/ 都是手动输入的话，可以正常弹出补全窗口， 如果Android 是按回车补全的话，再输入 / 就不会弹出补全选项，删掉/再输入/又可以正常弹出，尝试了半天，没有找到合适的办法

Bufix path complete

---

acm/acm.el

I can't find functions about tabnine in M-x and have to require this manually, so maybe it should be done in acm.el.

Require tabnine backend in acm.el.

---

acm/acm-backend-lsp.el
lsp-bridge.el

* acm/acm-backend-lsp.el (acm-backend-lsp-candidate-doc): Don't fetch the documentation if it is not empty.
* lsp-bridge.el (lsp-bridge-fetch-completion-item-info): Replace `label` with `key` in the judgment condition, make the logic consistent with `FileAction.completion_item_resolve`.
(lsp-bridge-completion--record-items): Reset fetch tick

Fix issue that sometimes can't get documentation

---

acm/acm-backend-telega.el

Since I can't find function remove-of and other acm backends use cl-remove-of.

Use cl-remove-if instead of remove-if

---

core/search_elisp_symbols.py

Support elisp symbol containing special characters, like "foo+bar", "foo?bar" and "foo*bar"

escape char in prefix before build regexp

---

acm/acm.el

* acm/acm.el (acm-init-colors): Correct backgournd when FORCE and background of `acm-default-face' are not nil.
Reproduce : (Set the background to "blue")
```sh
$ emacs -Q --eval "\
(progn
(require 'seq)
(setq user-emacs-directory
(car (seq-filter
#'file-exists-p
(list (format \"~/.emacs.d/%s/\" emacs-version)
(format \"~/.emacs.d/%s/\" emacs-major-version)
\"~/.emacs.d/\"))))
(setq package-user-dir (concat user-emacs-directory \"elpa/\"))
(package-initialize)
;; Add addtional local package here:
(add-to-list 'load-path \"~/repos/emacs-lsp-bridge\")
(require 'yasnippet)
(yas-global-mode 1)
(require 'lsp-bridge)
(set-face-background 'acm-default-face \"blue\")
(global-lsp-bridge-mode)
(add-hook 'emacs-startup-hook
(lambda ()
(load-theme 'tango-dark)
(switch-to-buffer \"*scratch*\") …
```

Fix background

---

lsp-bridge.el

I often try to reload with `M-x eval-buffer` in development, so it makes sense to fallback to `default-directory` when `load-file-name` is undefined

Use default-directory when load-file-name is NIL (eval-buffer)

---

README.md
langserver/intelephense.json
langserver/phpactor.json
lsp-bridge.el

[Phpactor](https://github.com/phpactor/phpactor) is an implementation of PHP's Language Server.

Add Phpactor as PHP's Language Server

---

acm/acm.el

`\t` (same as `(kbd "TAB")`) is already added, but it seems necessary to set `[tab]` to complete when Tab key is pressed in GUI Emacs.
Sorry if you didn't set it on purpose.

Add TAB key as acm-complete

---

langserver/phpactor.json

Sorry, I submitted the wrong definition information in my previous PR.
It looks like you can start the server properly with the new settings.
fixes https://github.com/manateelazycat/lsp-bridge/pull/393

Fix Phpactor LSP command

---

acm/acm.el
lsp-bridge.el

Language servers return the doc as Markdown, so it's convenient to render it.

Proposal: Activate lsp-bridge-render-markdown-content on acm-doc

---

acm/acm.el

``` elisp
(yas--template-content a-command-type-snippet)
;; => (progn ...)
(yas--template-content a-normal-type-snippet)
;; => "${1:$$...}"
```

Fix error when showing doc of a command type snippet

---

lsp-bridge.el

1. improve the candidate list in emacs-lisp mode by filtering out symbols which would return nil when applied by `fboundp, featurep, boundp, facep`
2. add local symbol to candidate list, the logic comes from `company-mode`
3. the timer of `lsp-bridge-elisp-symbols-timer` seems not working since no lsp-server would run for an emacs-lisp file, move the timer out of the condition block.
PTAL @manateelazycat

improve emacs-lisp candidate list

---

acm/acm.el

Macro `acm-cancel-timer` should define before using.
Defining to late will cause error `invalid function acm-cancel-timer` when we load native compiled lsp-bridge.

fix: acm-cancel-timer define to late

---

README.md
acm/acm.el

refs https://github.com/manateelazycat/lsp-bridge/pull/406#issuecomment-1334633908
Rendering immediately doesn't stress me out in my environment, so I'd like to be able to customize sync/async and invalidation.

Add acm-enable-doc-markdown-render for apply rich style

---

acm/acm-backend-citre.el

The function `citre-capf--get-collection` was removed in https://github.com/universal-ctags/citre/commit/00d915a

Fix acm-backend-citre-candidates

---

lsp-bridge.el

Solved https://github.com/meow-edit/meow/issues/383, I'm not sure whether this option could replace `lsp-bridge-not-in-mark-macro`, but I guess it's more universal for all macro related operatoins.

fix: hide completion during executing macros

---

lsp-bridge.el

Thank you for developing this wonderful package.
I propose new feature to allow popup completion menu for string interpolation.
This only works with string interpolation.
For example in python-mode,
no popup menu in string,
popup menu in string interpolation,

feat: Allow popup completion menu for string interpolation

---

README.md
README.zh-CN.md
lsp-bridge.el
lsp_bridge.py

添加了两个选项，能够让用户定义 langserver 和 multiserver 目录放自己的语言服务配置文件，如果用户定义了同名的配置文件，用户目录的优先级更高
像 volar 里面 tsdk 路径是写死的，之前想改比较麻烦，加了这两个选项后就比较灵活了，可以每个工程目录下放一个 volar.json ，实现不同的工程读不同的配置文件
配置例子：
``` elisp
(defun my-enable-lsp-bridge()
"Enable lsp bridge mode."
(require 'yasnippet)
(yas-minor-mode)
(require 'lsp-bridge)
(when-let* ((project (project-current))
(project-root (nth 2 project)))
(setq-local lsp-bridge-user-langserver-dir project-root
lsp-bridge-user-multiserver-dir project-root))
(lsp-bridge-mode))
```

add lsp-bridge-user-langserver-dir/lsp-bridge-user-multiserver-dir

---

lsp_bridge.py

https://github.com/xhcoding/lsp-bridge/commit/4f7fcec489b3981a5d2cf38d2063822a7a14ca54 removed it,  cause Windows startup server failed

fix server path

---

acm/acm.el

```
lsp-bridge/acm/acm.el: Warning: Pattern t is deprecated.  Use `_' instead
```
See https://www.gnu.org/software/emacs/manual/html_node/elisp/pcase-Macro.html
https://github.com/emacsmirror/emacs/blob/013655811aa1c89754372610c8c6ccccec166035/lisp/emacs-lisp/pcase.el#L948-L951

Use `_` (wildcard) instead of `t` for pcase

---

README.md
README.zh-CN.md

Feb 10, 2023，[sexpdata](https://pypi.org/project/sexpdata/#history) 发布了 0.0.4 版本，此版本会导致 epc 出现问题。故需指定版本为 0.0.3。

fix(docs): sexpdata version

---

core/lspserver.py

* core/lspserver.py: check settings if is None before calling len()
```python
>>> dict = {'settings': None}
>>> settings = dict.get('settings', {})
>>> type(settings)
<class 'NoneType'>
```
```python
settings = self.server_info.get("settings", {})
```
json配置里的settings为{}会被json解析为None，对于在字典中已经存在的关键字，值即使为None，get()也不会去取默认值，调用len()前需要再校验下settings的值

fix workspace/configuration handler when initial settings is empty

---

langserver/ruff.json

```
--- [13:24:32.587127] Recv window/logMessage notification from 'ruff' for project t.py
{
"params": {
"type": 4,
"message": "Running Ruff with: ['/sbin/ruff', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--line-length=500', '--ignore=F403,F405,E722, E402', '--stdin-filename', '/home/harumi/t.py']"
},
"method": "window/logMessage",
"jsonrpc": "2.0"
}
--- [13:24:32.592455] Recv window/logMessage notification from 'ruff' for project t.py
{
"params": {
"type": 4,
"message": "error: Unknown rule selector ` E402`"
},
"method": "window/logMessage",
"jsonrpc": "2.0"
}
```
should remove  whitespace before `E402`

fix ruff args

---

core/handler/__init__.py
core/handler/jdtls/jdtls_add_overridable_methods.py
core/handler/jdtls/jdtls_list_overridable_methods.py
core/utils.py
langserver/jdtls.json
lsp-bridge-code-action.el
lsp-bridge-jdtls.el
lsp-bridge.el

- 重构 `lsp-bridge-code-action--fix-do`
- 新增 `lsp-bridge-code-action-command-handlers` 非标准lsp的code action command handler注册表
- 支持 jdtls `overrideMethodsPromptSupport`

Support jdtls overrideMethodsPromptSupport

---

acm/acm-backend-citre.el
acm/acm-backend-elisp.el
acm/acm-backend-search-file-words.el
acm/acm-backend-tailwind.el
acm/acm-backend-telega.el
acm/acm-backend-tempel.el
acm/acm-backend-yas.el
lsp-bridge-ref.el
test/common.py
test/test.py
test/test_byte_compile.py

Hi! I've been trying to [package this extension with Nix](https://github.com/kira-bruneau/home-config/blob/d7e88d71f076867dbef3a2b3d5f66e167d949624/package/emacs/package/lsp-bridge/default.nix) and I ran into some problems with byte compilation:
```
acm/acm-backend-yas.el:188:10: Error: ‘add-to-list’ can’t use lexical var ‘candidates’; use ‘push’ or ‘cl-pushnew’
acm/acm-backend-tempel.el:24:16: Error: ‘add-to-list’ can’t use lexical var ‘candidates’; use ‘push’ or ‘cl-pushnew’
acm/acm-backend-elisp.el:112:10: Error: ‘add-to-list’ can’t use lexical var ‘candidates’; use ‘push’ or ‘cl-pushnew’
acm/acm-backend-telega.el:52:18: Error: ‘add-to-list’ can’t use lexical var ‘candiates’; use ‘push’ or ‘cl-pushnew’
acm/acm-backend-search-file-words.el:101:16: Error: ‘add-to-list’ can’t use lexical …
```

Support byte compilation

---

README.md
README.zh-CN.md
acm/acm.el
core/fileaction.py
core/lspserver.py
lsp-bridge.el
lsp_bridge.py

Using lsp-bridge directly in babel.  Enable by `lsp-bridge-enable-org-babel`.

feat: lsp for org-babel 

---

lsp-bridge-ref.el

Oops I realized I introduced a breaking change in [#557](https://github.com/manateelazycat/lsp-bridge/pull/557/files#diff-fc1ce441eeb8d0c03fec0d0e34c34d18cf9271370450afe309f12a9a296580daR590). `file-extensions` should be treated as a set here, not a list.
This fixes detecting when the ref list has already been filtered down to a single extension.

Fix detecting when refs are already filtered to a single extension

---

lsp-bridge.el

The elixir-ts-mode and heex-ts-mode packages are now part of emacs core and also have MELPA packages.  They both use the elixirLS server.
* lsp-bridge.el (lsp-bridge-single-lang-server-mode-list): Update elixirLS modes.

Add elixir-ts-mode and heex-ts-mode to use elixirLS

---

lsp-bridge.el

Sorry, missed this one. I tried adding heex-ts-mode, but the completion was a bit unpleasant as it returns mostly elixir, not heex suggestions.

Add elixir-ts-mode-hook to lsp-bridge-default-mode-hooks and to interpolation list

---

lsp-bridge.el

Previous method is slow and buggy, which requires saving the block before each edit. We can use `lsp-bridge-enable-org-babel` with native lsp bridge support to achieve better performance.

remove previous org bable complete

---

README.md
README.zh-CN.md
lsp-bridge.el

1. support `lsp-bridge-org-babel-lang-list` in lsp-bridge
2. remove begin_src and end_src when check org babel border

some improvements for org babel

---

lsp-bridge.el

use defvar change `position-before-jump` scope
make it can be keep in the function which is called after let binding

Fix issue #583 , by change the var scope

---

acm/acm.el

lsp bridge is enabled in markdown mode. On switching to markdown mode in magit (`forge-edit-post`), acm tries to determine what's the character type at point using treesitter in emacs 29 but failed because it does not know the language and there is no parser available
```
Debugger entered--Lisp error: (treesit-no-parser #<buffer 77>)
treesit-buffer-root-node(nil)
treesit-node-at(1)
(treesit-node-type (treesit-node-at (point)))
(string-equal (treesit-node-type (treesit-node-at (point))) "string")
(if (featurep 'treesit) (string-equal (treesit-node-type (treesit-node-at (point))) "string") (condition-case nil (progn (if (or (bobp) (eobp)) nil (save-excursion (and (nth 3 (or state ...)) (not (equal ... ...)))))) (error nil)))
acm-in-string-p()
(if (acm-in-string-p) (let* ((filename (and t …
```

do not use treesitter if no parser available

---

lsp-bridge-lsp-installer.el

By default, we use github codeium origin url
But we can use https://ghproxy.com/https://github.com/Exafunction/codeium/releases/download/language-server-v 
to quick access the download url via ghproxy.com

add codeium-download-url-prefix variable

---

core/lspserver.py

Fix lsp server (i.e. gopls ) not respond requests issue after lsp-bridge-code-action. Send { "applied": True } to lsp server after received workspace/applyEdit request and eval in emacs.

Send response after lsp workspace/applyEdit eval in emacs.

---

lsp-bridge.el

Added missing `rust-ts-mode-hook` to ` lsp-bridge-default-mode-hooks`

Add rust-ts-mode-hook to lsp-bridge-default-mode-hooks

---

core/lspserver.py

Fix typo in response result dict, change "," to ":".

Send workspace apply edit response, fix typo

---

acm/acm.el
lsp-bridge.el

~~It is broken again, do not merge plz~~
I wrap the function in before and after-change-functions with `save-match-data`, this should fix the problem of modifying match results. Let me know if you want me to properly indent the code, I was trying to make a minimum change here.

Save match data

---

acm/acm.el

`(help-function-arglist candidate-expand)` will not return original args list, if `candidate-expand` is a byte-compiled function.

fix parameter checking in `acm-preview-current`

---

README.md

The image links in `README.md` seem to be broken.
The quotations are chinese, which are invalid.

Fix image link, replace '“' and '”' with '"'

---

lsp-bridge.el

`tsx-ts-mode-hook` is missing from `lsp-bridge-default-mode-hooks`

Add `tsx-ts-mode-hook`

---

core/handler/completion_item.py

show detail when document is not available

---

core/handler/find_define.py
core/handler/find_references.py
lsp-bridge.el

It will be possible to intergrate lsp-bridge with other packages. 
In my case, I will try to find with tags backend when lsp failed to find def/ref.

Add fallback functions for searching def/ref

---

core/handler/find_implementation.py

fix wrong-number-of-arguments error

Fix find_implementation lsp-bridge-references--popup args

---

lsp-bridge.el

Fix for rename-file-advisor renaming current file accidentally

---

core/handler/hover.py

Fix erlang_ls popup documentation (#678)

---

README.md

It might be a typo, because I saw the elisp file name is: lsp-bridge-complete-manually

Update README.md - changed one typo

---

lsp-bridge-peek.el

在Peek时让definition在最顶端显示，让reference居中显示，以便更好地查看上下文。
麻烦大佬看一下🙏

Let the reference display in the center to view the relevant above.

---

acm/acm-backend-telega.el

Current implementation for username completion in telega have few issues:
1. It has  sync variant of fetching member list, because telega does not provide async API to fetch chat members
2. It uses potentially dangerous `buffer-list-update-hook` to do the job
3. It does some  job even if `lsp-bridge-mode` is disabled
This commit tries to resolve all these issues

Support for async telega--searchChatMembers in the telega 0.8.162

---

lsp-bridge.el

This PR adds support for [`clojure-ts-mode`](https://github.com/clojure-emacs/clojure-ts-mode), the next generation of clojure modes.
I was not sure how to do the indentation since the line becomes very long, so I left it as simple as possible. Can change it to align by splitting the `ts`-modes to a new line if that is prefered.

Add support for `clojure*-ts-mode`

---

lsp-bridge.el

I enable `lsp-bridge-find-def-select-in-open-windows`, but error occurs:
```
ERROR:epc:ReturnError([Symbol('void-function'), Symbol('return')])
```
I test the code in my repo, and this pr works.

fix void-function return

---

acm/acm-backend-tempel.el

修复使用 tempel 作为后端的报错：
1. delete undefined and unused variable `candidates`
2. replace undefined function `tempel--print-element` with `tempel--print-template`

fix: tempel backend error.

---

lsp-bridge.el

Add [`:safe` functions to defcustom](https://www.gnu.org/software/emacs/manual/html_node/elisp/Variable-Definitions.html#index-safe_002c-defcustom-keyword) to enable [local variables](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Local-Variables.html).
This isn't important for all custom variables, but it's useful to be able to override them on a per-project basis in [`.dir-locals.el`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Local-Variables.html).

Fix :type and add :safe function to defcustom variables

---

README.md
lsp-bridge-peek.el

Wanted to have a possibility to set the amount of lines that the peek window is moved up and down.

Lsp bridge peek file content scroll margin

---

core/lspserver.py

eslint lsp now needs full session settings

fix: fix eslint lsp config that workspace config requires full settings

---

lsp-bridge-diagnostic.el

rust analyzer can return diagnostics with start and end in different lines. This PR fixes diagnostics list to show entries across multiple lines.

fix: support multiline diagnostics

---

core/remote_file.py
lsp_bridge.py

Support ssh ProxyCommand option

---

README.md
README.zh-CN.md
lsp-bridge.el
lsp_bridge.py

1. add README for lsp-bridge-tramp usage
2. add lsp-bridge-tramp connection debug func

Lsp bridge tramp debug

---

langserver/kotlin-language-server.json

kotlin-language-server的配置格式修改了，现在修正了，可以开启inlayhint提示。
macos 下必须使用源码编译的kotlin-language-server, 系统安装包可能会出错。其他系统没测试。

update kotlin config

---

lsp-bridge-inlay-hint.el

我修改添加了一个函数：
```
(defun lsp-bridge-try-send-inlay-hint-request2 ()
(interactive)
(when lsp-bridge-enable-inlay-hint
(lsp-bridge-inlay-hint)))
```
使用发现，报错信息
```
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('sequencep'), Symbol('lsp-bridge-inlay-hint-label-text')])
```
另外我发现使用kotlin-language-server时，使用`lsp-bridge-try-send-inlay-hint-request2`函数，我在*lsp-bridge*没发现发送inlayhint信息，而在rust中有明显的发送信息。能否帮忙看看kotlin-language-server?
我确定kotlin-language-server有inlayhint信息，我使用lsp-mode已经显示出来了。

fix lsp-bridge-inlay-hint-label-text

---

lsp-bridge-ref.el

Due to a Language Server issue, ANSI escape codes are left unconverted to face when an empty interval is returned.

Apply face to an empty width match

---

lsp-bridge.el

`electric-indent-mode` has global state, so it affects all buffers that do not have lsp-bridge enabled.

Use electric-indent-local-mode instead of global electric-indent-mode

---

core/fileaction.py

without this fix, code action at point will list all the possible actions for the file regardless of the `range` argument in eslint server
this fix allows the server to filter the return value based on cursor position and selected range

fix: filter diagnostics within the range to send to code action request

---

core/remote_file.py
lsp-bridge.el

This change 
- rectify the misuse the name of `ssh_pub_key` 
-  add an option `lsp-bridge-user-ssh-private-key` for user to configurate the SSH private key they want to use.
Issue: The original code utilized a function named `ssh_pub_key` that misleadingly suggested it use a public SSH key to login SSH remote server. However, it is the **private SSH key** that are used for paramiko connection. This wrong naming could lead to confusion and potential misuse in the future.
You can look at the documentation https://docs.paramiko.org/en/latest/api/client.html#paramiko.client.SSHClient.connect
> key_filename ([str](https://docs.python.org/3.6/library/stdtypes.html#str)) – the filename, or list of filenames, of optional **private key(s)** and/or certs to try for authentication
> look_for_keys …

Enhance SSH Key Handling: support use of specified SSH private key

---

core/handler/find_references.py
core/remote_file.py
core/utils.py
lsp-bridge.el
lsp_bridge.py

I'm very happy to introduce to you this new functionality 😃  The update includes the ability to:
- Automatically restart the remote server process.
- Automatically reconnect to the remote server process in the event of a lost connection.
While I have thoroughly tested it in a local environment, I'm aware that it is a significant modification. Please take the necessary time to review and test. Ideally, I would have divided this update into several smaller PRs for ease of review; however, they are tightly coupling together, such a split would cost me too much time.
following I will explain what I did in detail.
this macro is missing a comma before `filehost` it should be `,filehost`, so it always result in an error and fall to the second clause of the `pcase`
```elisp
`(when-let ((buffer …
```

enable restart remote process and reconnect to remote process

---

lsp-bridge.el

This bug causes `wrong-number-of-arguments` error when `lsp-bridge-enable-log` is set to `t` and will cause Emacs remove `lsp-bridge-monitor-post-command` from `post-command-hook`.

fix lsp-bridge-try-completion bug with lsp-bridge-enable-log set to t

---

lsp-bridge.el
lsp_bridge.py

1. We should only send tramp file name localpart for 'search_paths_search'
2. Try to reconnect server after lsp-bridge-restart-process

Fix some errors with tramp

---

langserver/rust-analyzer.json

根据 
https://github.com/rust-lang/rust-analyzer/blob/d410d4a2baf9e99b37b03dd42f06238b14374bf7/crates/rust-analyzer/src/config.rs#L79-L194
获取的配置信息
测试例子可以使用 https://github.com/bitcoindevkit/bdk/blob/master/crates/esplora/src/blocking_ext.rs
测试例子是个workspace, 修改代码后，只会导致第一次save之后使用cargo check。
但以前的配置是每次save都会使用cargo check, 这个会卡住不给编译。
我忘记用什么工具格式化配置了，手动格式化的，有可能要重新格式化一次。

disable metadata and auto check after save

---

langserver/rust-analyzer.json

根据
https://github.com/rust-lang/rust-analyzer/blob/38f7a3498e0d5f0113294bbdc08f867cd527e65f/crates/rust-analyzer/src/config.rs#L127-L191
获取的配置信息
测试例子可以使用 https://github.com/bitcoindevkit/bdk

enable all feature, only check current crate in workspace

---

lsp-bridge.el

Added the support for the [vale-ls](https://github.com/errata-ai/vale-ls) language server. That use [vale](https://github.com/errata-ai/vale) to perform grammar and style checks on markdown files. It's working on my setup.

Added vale-ls for markdown grammer checking.

---

lsp-bridge.el

Supports obtaining paths with spaces

---

core/remote_file.py
core/utils.py
lsp-bridge.el
lsp_bridge.py

Add a `heartbeat` mechanism ffd0b982be317ac2c16b1ac22808c092414fe4ee for keeping remote connection alive to resovle #831 .
In the process of analyzing #831 ,I found some other bugs to fix here:
1. 431171c7bf192e7b809a4d970b65cde2d68d8609 `lsp-bridge-is-remote-file` needs synchronization with the server, so it is not real-time. We should not send requests for these remote files in updating to local servers or we will get unexpected errors. Before remote sync done, we just skip requests for these files.
2. c328cc8fc4627d72672c02ba4b88e713000009b1 We should call `sync_tramp_remote` with pure text buffer name.
3. ceb2f189a461c8c2efa0a2c43240d83d2f4ad408 When we have both opened remote files and local files and do `lsp-bridge-restart-process` in a local file buffer, we would get errors if we …

Fix remote server connection

---

acm/acm-backend-codeium.el
lsp-bridge.el

Add support for [php-ts-mode](https://github.com/emacs-php/php-ts-mode). This package is not yet available in any ELPA, but will be submitted to GNU ELPA in due course.
refs https://github.com/emacs-php/php-ts-mode/issues/55

Add php-ts-mode

---

core/handler/hover.py
langserver/jdtls.json
langserver/rust-analyzer.json

current jdtls lsp server textDocument/hover response contains a dict and then a plaintext, such as
```json
{
"contents": [
{
"language": "java",
"value": "org.springframework.boot.SpringBootApplication"
},
"Class that can be used to bootstrap ....."
]
}
```
Lsp-bridge renders a ```text``` block with plaintext.
This patch checks response for "language": "java", and render doc contents without modification when java found, since responding doc already in "markdown" format.
Configure "jdtls" and "rust-analyzer"  to request "markdown" format content in textDocument/hover requests.

Fix jdtls, rust-analyzer documentation issues.

---

lsp-bridge.el

When a tramp file is opened, its information is updated by calling `lsp-bridge-sync-tramp-remote` and will be finished in `lsp-bridge-update-tramp-file-info`. Before it is done, `lsp-bridge-remote-file-flag` is nil and related remote file info variables are not set. If we call file api this time, it will send the request to local lsp server(local epc call). Because the file is a remote file in fact, we won't get right result frome local server and it might leads to some unpredicatable exception. So we add check in `lsp-bridge-call-file-api` to skip the call if update is not finished.

Skip calling file api when we are updating tramp file info

---

lsp-bridge.el

`buffer-file-name` might have properties and we should only pass text string without any properties. Or we will get an error fo wrong number of arguments.

Get only text string for tramp file name

---

lsp-bridge.el

In the branch for indexing local files, it didn't remove local files from `buffer-list`. Calling `search_file_words_index_files` for local with remote file names will bring error. So we need to add a check rule `(file-remote-p elt)`.

Remove remote files on indexing local files

---

core/remote_file.py
lsp_bridge.py

Implement 3 file servers(FileSyncServer, FileElispServer and FileCommandServer) inherited from RemoteFileServer to unify implementation of file servers and reduce duplicate code and useless code so it will be clearer.

Unify remote file servers

---

core/remote_file.py
core/utils.py
lsp_bridge.py

Set a global `lsp_bridge_server` for all utils functions usage, and move `call_remote_rpc` into FileElispServer.

Unify remote functions in utils

---

core/remote_file.py
lsp_bridge.py

Add a queue for elisp channel to unify remote message process and parse json in common code instead of each handler.

Unify receive_remote_message for different file servers

---

core/remote_file.py
lsp_bridge.py

Use same function with different sender queue for different file servers and simplify sending 'Connect' message.

Unify send_remote_message to different file servers

---

core/handler/find_references.py
core/remote_file.py
core/utils.py
lsp-bridge-ref.el
lsp-bridge.el
lsp_bridge.py

1. Tweak the keys of the dict `host_names` storing ssh connection info so it will be compatible with class `paramiko.config.SSHConfigDict` which inherits the internal dict.
2. Also update remote information when `open_remote_file` in order to support jumping to references without using tramp.

Support jumping to references for remote files without tramp

---

core/remote_file.py
core/utils.py
lsp-bridge.el

If client does not send messages to the server for more than a specific time(e.g. 2h12min for me), the server will close the socket while the client can still send messages without error. However, the server will not receive and handle any more messages. In order to solve this issue, we add a mechanism to send heartbeats to the server to keep the connection alive.

Support heartbeat for remote connections

---

core/utils.py
lsp-bridge-ref.el
lsp-bridge.el
lsp_bridge.py

1. replace file-remote-p with string-match-p to support non-tramp usage.
2. clear the var `lsp-bridge-ref-open-remote-file-go-back-to-ref-window` after jump.
3. use `server_host` as key if it is already in host_names.
4. tweak the regular expression for remote file.

Fix some bugs for remote connection

---

acm/acm-backend-lsp.el

将输入特定的缩进改为直接调用 `indent-according-to-mode` ，以避免重复插入缩进。

A fixup for the completion of snippets

---

lsp-bridge.el

Tramp files with 'sudo' like methods are local files in fact. We should not try to sync tramp remote for these files.

Do not sync remote for local files with sudo

---

core/lspserver.py
core/remote_file.py
lsp_bridge.py

If client emacs exits directly, function `close_file` will not be called by client. So we just close all files when client disconnects.

Close all files in remote server when client disconnects

---

lsp-bridge-diagnostic.el

since flycheck / flymake can be enabled later with some interactive functions depending on the use cases.
with the `(unless lsp-bridge-diagnostic-enable-overlays)` check, the diagnostics are not available until the users start typing anything to trigger some lsp command.
if there wasn't a good reason (memory? maybe?), can we always enable it?

fix: always set diagnostics for first paint of flycheck/flymake update

---

acm/acm-backend-codeium.el
lsp-bridge.el

Added support for ruby-ts-mode.
ruby-ts-mode has become built-in packages in Emacs 29 and later.

Add ruby-ts-mode support

---

acm/acm-backend-jupyter.el
acm/acm.el
lsp-bridge.el

1. This backend can be activated by set `acm-enable-jupyter` to `t`
2. This backend only work when in a org-mode source code block and its language starts with `"jupyter"`
3. It still can make completion even though the `import` statement in a previous source code block
4. It need to start the jupyter in the org mode buffer first

feat: add emacs-jupyter completion backend for acm in org babel

---

lsp-bridge.el

it errors when the cursor is on typescript server's `move to new file...` code action.
i guess it is trying to preview the action but since the action is moving to a new file, the `buffer-file-name` is `nil` in this case. this only fixes the symptom, i am not sure about the cause.

fix: check buffer-file-name before checking if file is remote

---

core/ctags.py
core/remote_file.py
lsp-bridge.el

1. Accelerate the tramp file opening speed on already connected remote machines.
2. Adapt the remove_prefix function for Python versions prior to 3.9.
3. Use "ps | grep " to determine if the lsp_bridge.py process has started to prevent misjudgment.

Sync tramp info

---

lsp-bridge.el

https://github.com/clojure-emacs/clojure-ts-mode/blob/main/CHANGELOG.md#021-2024-02-14

fix: The name of the mode related to Clojure TS has been renamed.

---

acm/acm-backend-tempel.el

The variable `tempel-trigger-prefix` controls which prefix need to be input first before the completion can recognize it. For example, if there is a snippet "header" returned by `tempel--templates`, with `tempel-trigger-prefix` set to "t", "theader" will then expand to the snippet body.
This variable should be respected by ACM too.
The effects:
With prefix set, no tempel completion options show up:
If the prefix is entered, tempel snippets can be matched:
TAB, the completion expands:

Add support for "tempel-trigger-prefix"

---

core/handler/completion.py

Not deleted in https://github.com/manateelazycat/lsp-bridge/commit/f0eeb9ffbb363b6dd3ab675c57734db706c3393a.
-----
By the way, Python's default hashing algorithm has been replaced by SipHash13 since 3.11.
https://bugs.python.org/issue29410
I have not measured performance, but it is possible that the built-in [`hash`](https://docs.python.org/3/library/functions.html#hash) function may be superior to both `hashlib.md5` and a userland `fnv_1a` function in terms of collision resistance and performance when obtaining fixed-length hashes.

Remove unused hashlib imports

---

core/fileaction.py

I get:
```
--- [19:09:45.275665] Recv textDocument/signatureHelp response (32290) from 'rust-analyzer' for project
File "/home/exec/.emacs.d/straight/build/lsp-bridge/lsp_bridge.py", line 512, in event_dispatcher
getattr(self, func_name)(*func_args)
File "/home/exec/.emacs.d/straight/build/lsp-bridge/lsp_bridge.py", line 773, in _do
action.call(name, *args)
File "/home/exec/Projects/github.com/manateelazycat/lsp-bridge/core/fileaction.py", line 166, in call
getattr(self, method)(*args, **kwargs)
File "/home/exec/Projects/github.com/manateelazycat/lsp-bridge/core/fileaction.py", line 264, in try_code_action
self.send_code_action_request(self.single_server, *args, **kwargs)
File "/home/exec/Projects/github.com/manateelazycat/lsp-bridge/core/fileaction.py", …
```

Fix `Codeaction` to `CodeAction`

---

core/handler/completion.py

This Pr want to make completion `detail_label` for rust more friendly.
Before this PR:
After this PR:

Make completion detail_label for rust more friendly

---

core/copilot.py
lsp-bridge-lsp-installer.el

Can't use copilot and codeium in Windows because of the name issue.

Fix naming issues with copilot and codeium on Windows

---

core/codeium.py

Sometimes `insert_spaces` is passed a list type parameter, which then causes codeium to crash. It needs to be of type bool.

Fix insert_spaces type in codeium.py

---

core/remote_file.py
core/utils.py
lsp-bridge.el
lsp_bridge.py

Long story short, here are screenshots of lsp-bridge connecting to lsp-bridge server running inside [devcontainer](https://containers.dev/), this will definitely help the editing expereince of using Emacs to access files inside docker container.
Please see [my other project](https://github.com/nohzafk/devcontainer-feature-emacs-lsp-bridge) about the instructions of using lsp-bridge in devcontainer.
When container is restarted, opened buffers are no longer valid, automatically reconnect like `open remote SSH file` is not supported.

Support connect to lsp-bridge server running in devcontainer

---

README.md

Python distributions installed via `pyenv` require special treatment to work with lsp-bridge. `pyenv` is primarily a shell utility, and does not always integrate well with other processes since it assumes that the user has sourced extra definitions into their shell process before using it, and places a number of shim files
(which are just shell scripts that adjust the actual command to run based on the selected `pyenv` Python SDK version) before their executable counterparts in the PATH hierarchy. This messes with lsp-bridge, which requires an actual `python3` executable to launch the LSP server process, not a shim.
To fix this issue, users must set their `lsp-bridge-python-command` variable to the actual path to the `python3` executable for their selected Python version. This patch …

Add pyenv instructions to README

---

core/remote_file.py
lsp-bridge.el
lsp_bridge.py

1. Add timestamp for remote rpcs to avoid responses out of order.
2. When we do `lsp-bridge-restart-process` for remote usage, `hostnames` will be cleared in new lsp_bridge.py process. And we need to force reconnection to restart lsp-bridge successfully.

Enhancement for remote usage

---

acm/acm-backend-codeium.el
lsp-bridge.el

Adds support for the csharp tree-sitter mode included with emacs.
Also removes references to `csharp-tree-sitter-mode`, which is part of https://github.com/emacs-csharp/csharp-mode. It's been merged into emacs core and is no longer maintained as a separate repo.

feat: support treesit ts mode for csharp

---

core/remote_file.py
core/utils.py

Testing lsp-bridge in container gives me more edge case
This error happens constantly,  get_buffer_content is trying to read file content before handle_open_file finished, when it happens, lsp stops working, that's why I'm having trouble using language server inside container.
We need to wrap the file access opeartion with lock to ensure the access is atomatic.
error log
```log
File "/tmp/lsp-bridge/lsp_bridge.py", line 625, in event_dispatcher
getattr(self, func_name)(*func_args)
File "/tmp/lsp-bridge/lsp_bridge.py", line 886, in _do
action.call(name, *args)
File "/nix/store/f8ki1wxp84nj1nldjlj50y5wm5qknyn9-lsp-bridge-src-20240717-master/core/fileaction.py", line 166, in call
getattr(self, method)(*args, **kwargs)
File …
```

resolve race condition of get_buffer_content trying to read file content before handle_open_file finished

---

core/remote_file.py
core/utils.py
lsp_bridge.py

fix when lang_server is empty list
```log
file_dict after handle_open_file: 
File "/tmp/lsp-bridge/lsp_bridge.py", line 625, in event_dispatcher
getattr(self, func_name)(*func_args)
File "/tmp/lsp-bridge/lsp_bridge.py", line 879, in _do
open_file_success = self.open_file(filepath)  # _do is called inside event_loop, so we can block here.
^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/lsp-bridge/lsp_bridge.py", line 658, in open_file
lang_server_info = load_single_server_info(single_lang_server)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/lsp-bridge/lsp_bridge.py", line 994, in load_single_server_info
if os.path.exists(lang_server) and os.path.dirname(lang_server) != "":
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen genericpath>", line 19, in exists …
```

handle lang_server is empty list

---

README.md
README.zh-CN.md
core/remote_file.py
core/utils.py
lsp-bridge.el

- remove lsp-bridge-update-tramp-docker-file-mod-time, it is not usefull
- update readme with a tested example
- update readme of how to work with apheleia to auto-format remote docker file

works with apheleia to auto-format remote docker file

---

README.md
README.zh-CN.md
lsp-bridge.el

Remove it will make things just work, keeping buffer as a non-file buffer
- aphelia formatter will work with remote file
- use `set-visited-file-name` will result in saving the file twice, and we have to deal with buffer `modtime`, and unsaved change.
- keep the same logic as remote SSH file
Update README about how to use formatter with remote file.

Remove set-visited-file-name for remote docker file

---

lsp-bridge.el

jump to definition and jump back now works inside container

enable lsp-bridge-find-def to work inside container

---

lsp_bridge.py

1. We should wait for the signal before setting it.
2. A race condition exists where init_search_backends may finish running before waiting for `init_search_backends_complete_event` to be set. If this happens, the waiting process will never finish, blocking the entire process.

should wait for signal before set it

---

core/remote_file.py

- only use lock to prevent read file content before it is read
- remove unnecessary use of lock

reduce use of lock

---

README.md
core/remote_file.py
lsp-bridge.el
lsp_bridge.py

When using `find-file` to open a file in container, the TRAMP buffer is now setup as the **lsp-bridge buffer**
- we treat the TRAMP buffer as a non-file buffer by setting `buffer-file-name` to nil
- previous impl is not correct (create a new buffer for docker file and close the corresponding TRAMP buffer)
Update README for how to setup PATH for remote command execution, otherwise the formatter binary won't be found (for example `ruff`, even it is installed in container)
Support using `lsp-bridge-find-def` `lsp-bridge-find-def-return`  `lsp-bridge-find-def-other-window`  in container.
Text Matrix
| lsp-bridge-find-def-select-in-open-windows | docker file | lsp-bridge-find-def/-return                                                                | lsp-bridge-find-def-other-window |
| …

Support lsp-bridge in container correctly

---

acm/acm-backend-capf.el

适配了一下 sly，并且添加了 annotation，效果如下

acm-backend-capf adapt sly, add annotation.

---

core/lspserver.py
core/utils.py
lsp-bridge.el

修复clangd inlay hint不生效的问题

---

lsp-bridge.el

When searching .dir-locals.el first time in a project (not in dir-locals-directory-cache), dir-local-find-file will return string instead of a list

fix when dir-local-find-file return string first time

---

langserver/intelephense.json
langserver/phpactor.json

[`composer.json`](https://getcomposer.org/doc/04-schema.md) is known as the de facto project file for PHP.
* See also https://github.com/bbatsov/projectile/blob/master/projectile.el#L3354-L3356

Add project-files for PHP project

---

core/fileaction.py
lsp-bridge-diagnostic.el

Pass to python side and filter on python side.
This enables something like this to dynamically suppress some diagnostic.
```emacs-lisp
(defun leo/lsp-bridge-diagnostic-list-all ()
(interactive)
(let ((lsp-bridge-diagnostic-hide-severities '()))
(lsp-bridge-diagnostic-list)))
```

make lsp-bridge-diagnostic-hide-severities to works for list

---

core/lspserver.py

Some toolchains like rust-analyzer set up by rustup will look rust-toolchain.toml to decide which version to run. 
When there are multiple rust-toolchain.toml across subprojects/dependencies, it's important to sett cwd to the root project path.

setting cwd when launching lsp server

---

acm/acm.el

Otherwise, the doc will not be rendered in markdown like the attached gif because of this check.
https://github.com/manateelazycat/lsp-bridge/blob/db75a301714ca203798439bd087897c34dab0f8d/acm/acm.el#L1245

only re-insert doc when doc change

---

core/handler/rust_expand_macro.py

when using `lsp-bridge-rust-expand-macro` command
error msg
```
Error when processing response 4247
File "/Users/a/.emacs.d/var/straight/repos/lsp-bridge/core/handler/__init__.py", line 38, in handle_response
self.process_response(response)
File "/Users/a/.emacs.d/var/straight/repos/lsp-bridge/core/handler/rust_expand_macro.py", line 15, in process_response
eval_in_emacs("lsp-bridge-rust-expand-macro--update", response["name"], response["expansion"])
TypeError: 'NoneType' object is not subscriptable
```

fix expand rust macro

---

core/lspserver.py
langserver/vscode-json-language-server.json

vscode-json-language-server needs initiailizationOptions.provideFormatter to have documentFormattingProvider retunred by server.
ref: https://github.com/microsoft/vscode/blob/main/extensions/json-language-features/server/README.md#initialization-options

send formatting in capabilities and setup vscode-json-language-server

---

README.md
acm/acm-backend-tabby.el
acm/acm.el
lsp-bridge.el

1. add a tabbyml support by using [tabby.el](https://github.com/alan-w-255/tabby.el) as a client for sending request to tabby-agent
Notice:  tabby.el provide a tabby-mode which is laggy which use overlay and post-command-hook when used together with lsp-bridge directly, So I write this backend for acm.el.
2. tabby completion result maybe too late for the users completion, so I add a function `acm-backend-tabby-find-max-common` to drop the common suffix for users input and the prefix of the tabby's completion, eg: to write a bubble sort function
(1) the user type: `def bubb`
(2) trigger tabby completion
(3) the user contine typing: `def bubble_s`
(4) the tabby completion finished: `le_sort(arr):`
(5) merge the input and the completion:  `def bubble_sort(arr):`
3. **How to enable**: 
(1) …

Feat add tabbyml support

---

acm/acm-backend-capf.el
acm/acm.el
core/fileaction.py
lsp-bridge.el

1. fix acm-get-input-prefix-bound for org-mode
2. fix mismatch in capf for org (capf for org is disabled by default)
3. skip negative line in change_file
4. disable search_words_update for org babel

fix some org babel issues

---

lsp-bridge.el
lsp_bridge.py

In recent years, it has become very difficult to do a system-wide pip install as described in the README due to [PEP 668 – Marking Python base environments as “externally managed”](https://peps.python.org/pep-0668/).
[`pipx run`](https://github.com/pypa/pipx?tab=readme-ov-file#walkthrough-running-an-application-in-a-temporary-virtual-environment) transparently creates a virtual environment and automatically resolves the latest dependencies.
`pipx` supports [PEP 723 – Inline script metadata](https://peps.python.org/pep-0723/), so packages embedded in `lsp_bridge.py` scripts will be automatically installed.
The tradeoff is that we have to wait a few seconds on startup for the dependency checks, which was not a pain for me since it only happens when the server starts.
To enable `pipx` to …

Support "pipx run" command as lsp-bridge-python-command

---

lsp-bridge.el

单独为 lsp-bridge 创建一个 `python` 虚拟环境时（`lsp-bridge` 所有与`python`相关依赖都将安装这个环境中，如：`basedpyright`）。配置了`lsp-bridge-python-command` 值后，启动 `lsp-bridge` 时出现找不到语言服务器的命令的错误。
我觉得如果配置了 `lsp-bridge-python-command` ，那么其环境中安装的东西应该是 lsp-bridge 优先使用的，其次才查询系统环境的实现或者失败。
`python `虚拟环境未激活情况下，直接使用虚拟环境的`python`命令运行脚本时，其继承的是系统环境的`PATH`。所以当执行 `subprocess `和 `shutil.which `等代码时，其 `PATH` 未包含虚拟环境 `bin` 目录. 所以解决问题方法是将虚拟环境的 `bin` 目录直接添加 `PATH` 最前面。

lsp-bridge 找不到虚拟环境中安装的 lsp-server 命令 #1103

---

core/handler/code_action.py
core/handler/rename.py
core/utils.py

When I triggered a code action in a file over the tramp, the lsp_bridge.py output the following error, and the code action did not work.
```
--- [19:54:05.515935] Recv textDocument/codeAction response (26129) from 'ruff' for project sandbox
Error when processing response 26129
File "... /lsp-bridge/core/handler/__init__.py", line 38, in handle_response
self.process_response(response)
File "... /lsp-bridge/core/handler/code_action.py", line 37, in process_response
changes = item["edit"]["changes"]
KeyError: 'changes'
```
The `item["edit"]` is assumed to be a WorkspaceEdit instance and it looks to have one of (`changes ` or `documentChanges` ).
See:  https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit …

Fix: lsp_bridge.py raises a `KeyError` when a code action is triggered in tramp.

---

.github/workflows/test.yml
README.md
core/tabnine.py

fix version function for python 3.13

---

lsp_bridge.py

`packaging` is imported by core/tabnine.py. Let's include it in the pipx dependencies as well. Otherwise, `pipx run lsp_bridge.py` may complain with errors
```
File "lsp_bridge.py", line 55, in <module>
from core.tabnine import TabNine
File "core/tabnine.py", line 31, in <module>
from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

Include `packaging` in pipx dependencies

---

lsp-bridge.el

The `lsp-bridge-elisp-get-filepath` appears to enter infinite-loop when yaml-mode.
1. setup a yaml lsp server (`npm install -g yaml-language-server`)
2. open a yaml file (`test.yaml`)
3. add some valid items (`a: 1`)
4. move the cursor to beginning-of-buffer
5. type any characters, see the example below.
ex.
```yaml
<- type here in yaml model
a: 1
b: 2
c: 3
```
In the while loop of the `lsp-bridge-elisp-get-filepath`  function, if `file-beg` variable has `1` and the substring does not match any existing file paths,  the result of `(goto-char (1- file-beg))` would not change cursor position (`file-beg` is still `1`) and repeat the same loop infinitely.
I added a check to see whether the `file-beg` variable reaches the `beginning-of-buffer` or not.
I could not observe the problem in other …

fix infinite-loop in `lsp-bridge-elisp-get-filepath` when yaml-mode

---

lsp_bridge.py

lsp_bridge.py中的turn_off_by_single_file函数缺失self参数，会导致报错。

fix: Add missing self parameter to turn_off_by_single_file

---

lsp-bridge.el

Show completion when meow package is required but meow mode is disabled
The same applies to evil

fix: Show completion behavior of meow and evil

---

lsp_bridge.py

#1188 introduced a change that unintentionally starts copilot, even if you don't use it. If you didn't have nodejs installed, this would break lsp-bridge.

fix: don't start copilot when not used

---

README.md
lsp-bridge.el

The [uv](https://docs.astral.sh/uv/)  is another popular package management tool and supports inline metadata format as the pipx did. see, https://docs.astral.sh/uv/guides/scripts/#declaring-script-dependencies 
The uv is expected to be very fast so it is nice if lsp-bridge also supports `uv run`.

Add support of `uv run` as well as pixed did.

---

lsp-bridge-imenu.el
multiserver/angular_template_html.json
multiserver/angular_template_typescript.json
multiserver/basedpyright_ruff.json
multiserver/css_emmet.json
multiserver/css_tailwindcss.json
multiserver/html_emmet.json
multiserver/html_tailwindcss.json
multiserver/jedi_ruff.json
multiserver/pylsp_ruff.json
multiserver/pyright-background-analysis_ruff.json
multiserver/pyright_ruff.json
multiserver/python-ms_ruff.json
multiserver/qmlls_javascript.json
multiserver/typescript_eslint.json
multiserver/typescriptreact_eslint.json
multiserver/volar_emmet.json

Call the value of `lsp-bridge-imenu-function` instead of calling _it_.
Also fixed error when using multiserver:
```
File "/home/deirn/.config/emacs/elpaca/builds/lsp-bridge/lsp_bridge.py", line 675, in event_dispatcher
getattr(self, func_name)(*func_args)
File "/home/deirn/.config/emacs/elpaca/builds/lsp-bridge/lsp_bridge.py", line 967, in _do
action.call(name, *args)
File "/home/deirn/Documents/github.com/deirn/fedoracfg/config/emacs/elpaca/repos/lsp-bridge/core/fileaction.py", line 171, in call
method_server_names = [self.multi_servers_info[method]]
KeyError: 'imenu'
```

Fix Imenu comprehension

---

core/handler/document_symbol.py

error log :
```
--- [01:34:56.649630] Recv $/progress notification from 'rust-analyzer' for project main.rs
--- [01:35:19.444912] Send textDocument/inlayHint request (41083) to 'rust-analyzer' for project main.rs
File "/Users/gerald/.emacs.d/var/straight/repos/lsp-bridge/core/handler/document_symbol.py", line 32, in process_response
if symbol["children"]:
~~~~~~^^^^^^^^^^^^
KeyError: 'children'
```

check children in symbol

---

acm/acm-backend-yas.el

yas-expand-snippet needs yas-minor-mode enabled. Use the buffer local state to enable yas conditionally. Otherwise selecting candidates throws error message "‘yas-expand-snippet’ needs properly setup ‘yas-minor-mode’"

fix: do not show yasnippets candidates if minor mode not enabled

---

test/common.py

Tempel now requires Emacs 29+, making the test fail.
To fix this and future errors, use Quelpa to pin the package version to specific commit.
https://github.com/minad/tempel/commit/79e0538f7c273a1ae73ec3f8c77563e38ed31e84

test: use quelpa to pin package version
