manateelazycat/lsp-bridge

- README.md
- core/fileaction.py
- core/lspserver.py
- lsp-bridge.el
1. simple support solargraph.
2. added some try..except to make thread more rubost.
> Support solargraph and make thread more rubost.

- lsp-bridge.py
> Fix crash while closing file

- core/fileaction.py
- langserver/texlab.json
- lsp-bridge.el
添加 latex 支持，图标和annotation能用但不够好用。
1. 图标和annotation 显示有时候会慢一拍
2. annotation 不能带空格，否则 eval_in_emacs 参数转换时候会出错
doc 解析太麻烦还没想好怎么做
> Add support for latex

- core/fileaction.py
> Fix: completion item without "kind"

- core/lspserver.py
like pyright/rust-analyzer/ts-ls
> fix protocol exchange problem to some lsp servers under Windows

- core/fileaction.py
- core/lspserver.py
- core/utils.py
- lsp-bridge.el
> Fix encoding string with spaces

- lsp-bridge.el
Add keymap for lsp-bridge-mode.
> Add keymap for lsp-bridge-mode.

- core/utils.py
- lsp-bridge.el
> Use sexpdata for serialization.

- README.md
- langserver/bash-language-server.json
- lsp-bridge.el
> Add bash support.

- lsp-bridge.el
Fix `void-function lsp-bridge--with-file-buffer` error.
> Move function declaration.

- core/fileaction.py
`textDocument/hover` spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover
> Handle `textDocument/hover` response according to lsp spec

- core/fileaction.py
- core/lspserver.py
> Distinguish message type reqeust/response/notification

- lsp-bridge-ref.el
> Fix the parent group of `lsp-bridge-ref'

- core/fileaction.py
- lsp-bridge.el
[![O6EfY9.gif](https://s1.ax1x.com/2022/05/14/O6EfY9.gif)](https://imgtu.com/i/O6EfY9)
通过 lsp-bridge-enable-auto-import 并重启 lsp-bridge 可以控制是否开启 auto-import
> Support auto-import

- core/fileaction.py
- lsp-bridge.el
> Beautify the document

- core/fileaction.py
- core/lspserver.py
https://github.com/manateelazycat/lsp-bridge/issues/72
还是加一个这个吧? 基本能解决 windows 中文问题,，对类 unix 系统没影响，windows 再有其它奇葩编码问题就不处理了
> add encoding="utf-8" in open

- README.md
- langserver/elm-language-server.json
- lsp-bridge.el
This pull request add support for [elm](https://elm-lang.org/) language, with [elm-language-server](https://github.com/elm-tooling/elm-language-server)
> Add elm support

- core/fileaction.py
- core/handler/find_references.py
- core/handler/hover.py
- core/handler/prepare_rename.py
- core/utils.py
- lsp_bridge.py
写pr 的时候 我这边总是自动删除行尾空格，干扰review .
本次提交无实录质代码修改。
> 删除py 行尾的空格，

- core/handler/completion.py
- core/lspserver.py
- lsp-bridge.el
> enable deprecatedSupport

- README.md
- README.zh-CN.md
I think there is a minor typo. Thanks for the wonderful work!
> Correct the spelling of the command to install fonts

- lsp-bridge.el
发现 rust-analyzer 在 macos 下不能补全，最终发现问题在于工程在一个软连接目录中。
git 得到的 project_path 识别到了真实路径，而其他交互都使用的软连接名字。
这个修改, 使发送到 lsp-bridge 的所有文件名都是 truename。
> use true name for soft-link files

- core/handler/hover.py
> Check whether the type of hover document is markdown

- core/handler/completion_item.py
> Fix "completionItem/resolve" response's documentation is None.

- acm/acm-backend-tempel.el
- acm/acm.el
- test/test.py
见 https://github.com/minad/tempel
是一个比 yas 简单的 snippets 补全包。
> add acm-backend-tempel

- core/lspserver.py
> Avoid causing lsp-bridge to crash due to lsp process exit early.

- core/search_file_words.py
> Enhance word split

- core/search_file_words.py
> Fix RuntimeError: Set changed size during iteration.

- lsp-bridge.el
> add chinese lighter for the mode-line

- README.md
- README.zh-CN.md
- langserver/groovy-language-server.json
- lsp-bridge.el
> Add groovy-language-server

- core/search_file_words.py
避免一个文件解码错误影响后面文件的解析，也避免一个文件出错，不断循环去解析先前相同的文件
> fix UnicodeDecodeError

- lsp-bridge.el
> add posframe & markdown-mode to Package-Requires

- README.md
- README.zh-CN.md
- langserver/rnix-lsp.json
- lsp-bridge.el
[`rnix-lsp`](https://github.com/nix-community/rnix-lsp) is a (WIP) language server for nix
> add rnix-lsp support

- acm/acm-quick-access.el
- acm/acm.el
quickly select candidate by pressing M-0, M-1... in acm-mode-keymap
reference:
https://github.com/company-mode/company-mode/blob/73a3bdea0a82731ba8fb5890b6cdcba5b9dd44b7/company.el#L705-L813
> feat: quickly acces candidate

- README.md
- README.zh-CN.md
- langserver/rlanguageserver.json
- lsp-bridge.el
Add R's languageserver for ess-r-mode.
> Add R's languageserver for ess-r-mode

- core/fileaction.py
- core/lspserver.py
- lsp-bridge.el
send different textDocument/didChange message based on server's response
> Text sync option

- README.md
- README.zh-CN.md
- langserver/cmake-language-server.json
- lsp-bridge.el
> Add cmake language server

- lsp-bridge-jdtls.el
refer more details at https://github.com/manateelazycat/lsp-bridge/issues/319.
> Solve jdtls json read error. (#319)

- acm/acm-backend-lsp.el
This change fixes #330 and #327
> Fixes #330 and #327

- README.md
- README.zh-CN.md
Set lsp-bridge-enable-search-words to nil but acm still complete
search words, have to set acm-enable-search-words to nil.
> Add search words description to README

- acm/acm-backend-citre.el
- acm/acm-backend-elisp.el
- acm/acm-backend-english.el
- acm/acm-backend-lsp.el
- acm/acm-backend-path.el
- acm/acm-backend-search-words.el
- acm/acm-backend-tabnine.el
- acm/acm-backend-telega.el
- acm/acm-backend-tempel.el
- acm/acm-backend-yas.el
- acm/acm-quick-access.el
- acm/acm.el
Add acm customization group, remove some hard-coded backend part in `acm-fetch-candidate-doc`, `acm-hide`, `acm-complete`, `acm-menu-render-items` and `acm-doc-show`.
> add ACM customization group

- README.md
- README.zh-CN.md
- langserver/swift-sourcekit.json
- lsp-bridge.el
add swift sourcekit lsp server support
> add swift sourcekit lsp server support

- README.md
- core/lspserver.py
- langserver/omnisharp-window.json
- langserver/omnisharp.json
- lsp-bridge.el
添加c#服务器，暂时语法检查没发用。我没windows机器，所以windows那边没测过。
> add omnisharp

- acm/acm-backend-yas.el
- refactor: get yas candidates from `yas--tables` rather than parsing `(car yas/root-directory)`. The latter would only support first snippet directory and omit others, now all sniippets are read from `yas--tables`.
- feature: change option `acm-backend-yas-show-trigger-keyword`, now self-defined string is supported.
- feature: add option `acm-backend-yas-match-by-trigger-keyword`, snippet candidates are matched by file names by default, now trigger keyword is supported.
- feature: add option `acm-backend-yas-show-doc-expansion`, now snippet doc showing in expansion style is supported.
> feat(acm-backend-yas): use yasnippt api instead

- langserver/volar.json
- langserver/volar_darwin.json
- langserver/volar_windows.json
> fix: repair lsp-volar config

- lsp-bridge.el
Use buffer local face instead.
> Don't change markdown face directly

- lsp-bridge.el
> support popup for code action

- acm/acm-backend-yas.el
- perf: cache templates for major-mode switch and yas snippet loading
- fix: sort before slice to promote completion candidates accuracy
- style: move trigger information ahead when match-by-trigger is true
> refactor(acm-backend-yas): a few improvements

- lsp-bridge.el
> support diff preview for code action

- core/search_sdcv_words.py
- resources/pinyin.ifo
对 search_sdcv_dictionary 进行了拓展，能够同时用英文、拼音来搜索单词。
寻找了一个通过中文反查英文的词典，进行了一系列的清洗。转换出一个新的词典pinyin, python 加载以后是一个json格式类似：
``` json
{
"haidao": {
"pirate": "海盗",
"seaway": "海道"
}
}
```
对代码的改动不大，主要还是做了一个拼音词典。
拼音查询都是用的精准匹配，并且和英文匹配同时使用，进行拼音查英文和单词匹配不用做任何的切换。
> feat: extend search_sdcv_dictionary to support search by pinyin.

- core/lspserver.py
- langserver/pyright.json
按照 https://emacs-china.org/t/lsp-bridge/20786/2570 ， 提交一个补丁，支持 pyright 的 后台分析。
> add pyright background index

- lsp-bridge.el
1. Show code action and previewer in one frame.
2. Use temp buffer instead of temp file
3. Cache previous results
> improve code action preview

- lsp-bridge-call-hierarchy.el
- lsp-bridge.el
1. extend highlight face after EOL
2. adjust position to avoid out of screen
> improve code action posframe

- acm/acm-frame.el
- acm/acm.el
- lsp-bridge-call-hierarchy.el
- lsp-bridge-frame.el
- lsp-bridge.el
let acm, code-action and call-hierarchy share `lsp-bridge-frame` to create and mantain pos frame.
> add frame tools

- README.md
- README.zh-CN.md
- langserver/ansible-language-server.json
For https://github.com/manateelazycat/lsp-bridge/issues/471
> Add `ansible-language-server`.

- lsp-bridge-diagnostic.el
- lsp-bridge.el
Maybe we can hover error for diagnostics
> add hover error for diagnostics

- README.md
> Add missing Python dependency for pip command.

- lsp-bridge.el
Signed-off-by: WeiZhang <kweizh@gmail.com>
> feat: support treesit ts mode for go,c,rust,yaml

- README.md
- README.zh-CN.md
- core/handler/__init__.py
- core/handler/document_symbol.py
- core/lspserver.py
- lsp-bridge.el
- multiserver/css_emmet.json
- multiserver/html_emmet.json
- multiserver/jedi_ruff.json
- multiserver/pylsp_ruff.json
- multiserver/pyright-background-analysis_ruff.json
- multiserver/pyright_ruff.json
- multiserver/python-ms_ruff.json
- multiserver/qmlls_javascript.json
- multiserver/volar_emmet.json
Maybe we can use `textDocument/documentSymbol` to make `which-func-mode` fast
> Support documentSymbol for fast which-func

- core/utils.py
> fix epc_arg_transformer

- langserver/julials.json
- lsp-bridge.el
add Julia support and solved the issue #354 by myself...
The json file references to the log info and these pages
- https://github.com/gdkrmr/lsp-julia/blob/master/lsp-julia.el
- https://github.com/julia-vscode/LanguageServer.jl
- https://github.com/manateelazycat/lsp-bridge/issues/354#issuecomment-1342040518_
> Add Julialang support

- core/fileaction.py
- lsp-bridge.el
- lsp_bridge.py
1. kill all lsp server when exit
2. update server info when server change
3. create local values (such as acm-backend*) even no babel at current point.
> fix some issues for org babel

- core/lspserver.py
- langserver/vscode-eslint-language-server.json
- lsp-bridge-code-action.el
- multiserver/typescript_eslint.json
> Eslint support

- lsp-bridge.el
Use post-affiliated instead of begin to support code block with #+name https://github.com/manateelazycat/lsp-bridge/pull/576#discussion_r1148573154.
> use post-affiliated as bop for org babel

- README.md
- README.zh-CN.md
- langserver/verible.json
- lsp-bridge.el
Support the [newly announced](https://www.chipsalliance.org/news/integrating-language-server-protocol-in-verible/) verilog language server: [verible](https://github.com/chipsalliance/verible).
> feat: add verilog's verible language server

- core/codeium.py
- lsp-bridge.el
- lsp_bridge.py
Fix the delay in displaying the autocomplete items for Codeium.
> Support CancelRequest for Codeium

- acm/acm.el
- core/codeium.py
- core/utils.py
- lsp-bridge.el
* Add Codeium continuous completion feature
* No longer fixing the delayed display of complete items for Codeium
* When Codeium local server fails to start, kill the old process
> Add Codeium continuous completion

- acm/acm-backend-codeium.el
- core/codeium.py
- lsp-bridge.el
1. Drop old post requests
2. Get utf-8 cursor offset in python
3. Fix label display
> improve codeium

- core/codeium.py
Because
(I removed CancelRequest earlier)
> Add CancelRequest again

- README.md
- README.zh-CN.md
- acm/acm-backend-citre.el
- acm/acm-backend-codeium.el
- acm/acm-backend-lsp.el
- acm/acm-backend-path.el
- acm/acm-backend-search-file-words.el
- acm/acm-backend-search-sdcv-words.el
- acm/acm-backend-tabnine.el
- acm/acm-frame.el
- acm/acm.el
- lsp-bridge.el
> feat: add tab-and-go completion

- core/handler/completion_item.py
> fix: do not rely on document for additional edits

- acm/acm-backend-copilot.el
- core/copilot.py
- lsp-bridge-lsp-installer.el
- lsp_bridge.py
1. add node version check
2. add status check
3. improve npm package lookup
> improve copilot

- core/copilot.py
insert_spaces will be [] if indent-tabs-mode == t
> fix: fix copilot if indent-tabs-mode is t

- acm/acm-backend-citre.el
- acm/acm-backend-codeium.el
- acm/acm-backend-copilot.el
- acm/acm-backend-elisp.el
- acm/acm-backend-lsp.el
- acm/acm-backend-path.el
- acm/acm-backend-search-file-words.el
- acm/acm-backend-search-sdcv-words.el
- acm/acm-backend-tabnine.el
- acm/acm-backend-tailwind.el
- acm/acm-backend-telega.el
- acm/acm-backend-tempel.el
- acm/acm-backend-yas.el
> Disable byte compile for acm backend

- lsp-bridge-diagnostic.el
Integration with [flymake-bridge](https://github.com/liuyinz/flymake-bridge) to provide interface for traditional tools.
> provide diagnostic interface for flymake/flycheck frontend

- langserver/vscode-css-language-server.json
Add missing option to start css-lsp
> fix css validProperties null error

- lsp-bridge.el
> Make `lsp-bridge-complete-other-backends` more robust.

- README.md
- README.zh-CN.md
- core/handler/__init__.py
- core/handler/semantic_tokens.py
- core/lspserver.py
- lsp-bridge-semantic-tokens.el
- lsp-bridge.el
> Highlight some semantic tokens

- langserver/kotlin-language-server.json
also see https://github.com/emacs-lsp/lsp-mode/pull/4197
> enable kotlin language server inlayhint feature

- core/handler/find_references.py
- core/remote_file.py
- core/utils.py
- lsp_bridge.py
support lsp-bridge-find-reference with tramp
> support find-ref with tramp

- lsp-bridge.el
> Update docstrings to include all possible choices

- core/remote_file.py
- lsp-bridge.el
reconnect remote host when socket is broken
> reconnect remote host when socket is broken

- lsp-bridge-ref.el
1. Delete other windows when finding references, default t.
2. Open file in the original window if we do not delete other windows, default nil.
> Support new features for finding refereneces

- core/handler/completion.py
> Fix missing import completions for same symbol name in multiple files.

- lsp_bridge.py
Classify functions of class `LspBridge` into different groups to make code clearer.
> Classify functions of class LspBridge

- langserver/dart-analysis-server.json
Mentioned in [#851](https://github.com/manateelazycat/lsp-bridge/issues/851)
> Make completion of functions more comfortable

- lsp-bridge.el
While opening remote files without tramp, these buffers' `(buffer-file-name)` are `nil`. So we exchange the order of conditions check to avoid nil buffer name for remote files without tramp.
> Fix file api for remote files without tramp

- lsp_bridge.py
Fix commit 8373691e003fc5c8da2fe1134d5dc9fbd9171f52
Tested 3 cases:
1. tramp name without ip `/ssh:user@host:~/...`
2. tramp name with ip `/ssh:user@ip:~/...`
3. open remote file `user@ip:port:~/...`
> Fix the resolution of ssh host name with ip host for tramp

- acm/acm.el
> Let acm-candidate-fuzzy-search accept rx regexp.

- acm/acm-backend-codeium.el
line 120 is already here, duplicated
> delete duplicated line

- core/lspserver.py
- lsp-bridge.el
this PR
1. adds mode hook for graphql-ts-mode
2. fix initialization of working directory is not correct
> Graphql ts mode support and initialization fix

- core/utils.py
dont know if thats wanted but i apparently had a random list in one of my paths which tripped lsp-bridge up.
> extra path sanitation

- langserver/volar.json
- langserver/volar_darwin.json
- langserver/volar_windows.json
see https://github.com/joaotavora/eglot/discussions/1395#discussioncomment-9280456
设置vue hybrideMode 为false，这样volar才正常工作。
> set vue hybrideMode false

- acm/acm-backend-ctags.el
- core/handler/prepare_rename.py
- core/handler/range_formatting.py
- core/handler/rename.py
- core/handler/workspace_symbol.py
support rename, range_formatting, workspace_symbol on tramp file
> support rename, range_formatting, workspace_symbol on tramp file

- core/handler/peek.py
- core/remote_file.py
- lsp-bridge-peek.el
- lsp-bridge.el
- lsp_bridge.py
support peek and format for tramp files
> support peek and format for tramp files

- lsp-bridge-imenu.el
user can customize which modes use the imenu command.
> add lsp-bridge-raw-imenu-modes

- lsp-bridge.el
Adds support for the docker tree-sitter mode included with emacs.
> feat: support treesit ts mode for dockerfile

- lsp-bridge.el
Adds support for the nix tree-sitter mode: https://github.com/nix-community/nix-ts-mode/
> feat: support treesit ts mode for nix

- lsp-bridge.el
> fix dir-locals-find-file returning directory with trailing /

- langserver/texlab.json
based on
https://github.com/latex-lsp/texlab/blob/master/crates/distro/src/language.rs
> fix texlab langagueIds

- acm/acm.el
Removing same candidates between lsp, workspace-symbol and search words.
Before 
After
> Remove duplicate candidates

- core/codeium.py
- lsp-bridge.el
- lsp_bridge.py
Support new version codeium
fix #1036
> fix codeium failed with 500

- core/handler/completion_workspace_symbol.py
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_symbol
> workspace/symbol should use SYMBOL_MAP instead of KIND_MAP

- core/handler/hover.py
- lsp-bridge.el
ref: https://github.com/rust-lang/rust-analyzer/pull/9693
> support ranger hover (for rust-analyzer now)

- lsp-bridge.el
修改这个bug：https://github.com/manateelazycat/lsp-bridge/issues/1139
我的emacs版本是31，大佬看下这样改可以不
> 处理yas 展开过程中, narrow-to-region, 导致 change-file错误

- core/lspserver.py
> fix watchdog error

- README.md
- README.zh-CN.md
- lsp-bridge.el
- lsp_bridge.py
- test/lsp-bridge-test.el
> fix(#1165): use a more reasonable option for log

- lsp-bridge-imenu.el
Sorry i have overseen that function call
> Fix missing replaced function

- core/copilot.py
> fix: corrected typo in `accept` method name

- core/copilot.py
Implemented inline completions.
Modified to call the `textDocument/inlineCompletion` API during completion, referring to https://github.com/github/copilot.vim/.
Reference:
https://github.com/github/copilot-language-server-release?tab=readme-ov-file#inline-completions
> feat: implement inline completion support for copilot

- core/copilot.py
- lsp_bridge.py
This change modifies the code to provide the workspace folder information to Copilot, aiming to enhance the accuracy of Copilot's code completion suggestions.
> feat: add workspace folder support to copilot.

- lsp-bridge-dart.el
> change dart appearence
